#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox-esr desktop='^1'
bspc rule -a Code desktop='^2'

pkill polybar
polybar main &

feh --bg-scale ~/Pictures/wallpapers/rick.png

picom &

setxkbmap -layout us,ru -option grp:alt_shift_toggle
